  
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    allowed_updates:
      - match:
          update_type: "security"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "tboeghk"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    reviewers:
      - "tboeghk"