name: geoip weekly release
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 3 * * WED'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build api
      run: mvn clean verify
    - name: Build Docker image
      uses: actions/docker/cli@master
      with:
        args: "build -t observabilitystack/geoip-api:latest -t observabilitystack/geoip-api:$(date +%Y-%V) ."
    - name: Log into Docker Hub
      uses: "actions/docker/login@master"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: actions/docker/cli@master
      with:
        args: "push observabilitystack/geoip-api:$(date +%Y-%V) observabilitystack/geoip-api:latest"

