# This workflow checks out code, builds an image, performs a container image
# vulnerability scan with Anchore's Grype tool, and integrates the results with GitHub Advanced Security
# code scanning feature.  For more information on the Anchore scan action usage
# and parameters, see https://github.com/anchore/scan-action. For more
# information on Anchore's container image scanning tool Grype, see
# https://github.com/anchore/grype
name: "Code Analysis: Anchore Container Scan"

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#    paths:
#      - Dockerfile
#  pull_request:
#    branches:
#      - master
#    paths:
#      - Dockerfile
#  schedule:
#    - cron: '29 21 * * 1'

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        build-args: |
          MAXMIND_LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }}

    - name: Scan image
      uses: anchore/scan-action@v3
      with:
        image: "localbuild/testimage:latest"
        acs-report-enable: true
        fail-build: false
        debug: true
        severity-cutoff: critical

    - name: Upload image scan report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
